### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by nckng** [nckng/Cherry_MX_Brown_Mykolyk#3]
I'm doing 5 i guess?

**Comment by Shaumik-Ashraf** [comment]
I did the work for 5 (it wasnt much)

**Comment by Shaumik-Ashraf** [comment]
but i cant compile for somereason bc of windows

**Comment by nckng** [comment]
r u using git bash?

**Comment by Shaumik-Ashraf** [comment]
yea
althou i finally just fixed the problem

**Comment by nckng** [comment]
Alright so whats left?

**Comment by Shaumik-Ashraf** [comment]
my code just compiled; i think we're done now

**Comment by Shaumik-Ashraf** [comment]
want me to push?

**Comment by nckng** [comment]
Yeah go for it
ill edit and add if needed

**Comment by Shaumik-Ashraf** [comment]
okay, i'll also give u some credit on the devlog

**Comment by Shaumik-Ashraf** [comment]
pushed!

**Comment by nckng** [comment]
we have a devlog?

**Comment by manderson0** [comment]
wait does the code for 4 work? I just did it :/
